version: 2
multi-ecosystem-groups:
  repository-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: 09:00
      timezone: Europe/Madrid
    commit-message:
      prefix: chore(deps)
updates:
  - package-ecosystem: npm
    directory: /
    cooldown:
      default-days: 7
      semver-minor-days: 7
      semver-patch-days: 3
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    patterns:
      - "*"
    multi-ecosystem-group: repository-dependencies
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    patterns:
      - "*"
    multi-ecosystem-group: repository-dependencies
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    patterns:
      - "*"
    multi-ecosystem-group: repository-dependencies
    allow:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
